version: "3"
services:
  server:
    image: bletive/idp-hub1
    links:
      - database
    ports:
      - "5000:5000"
    tty : true
    networks:
      - shukrnet

  database:
    image: bletive/database
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - shukrnet

  client:
    #build: ./client
    image: bletive/client_idp
    depends_on:
      - server
    links:
    - server
    ports:
      - "6666:6666"
    stdin_open : true
    tty : true
    networks:
      - shukrnet

  admin:
    depends_on:
      - database
    #build: ./admin
    image: bletive/admin_idp
    links:
      - "database"
    ports:
      - "5002:5002"
    stdin_open : true
    tty : true
    networks:
      - shukrnet


networks:
  shukrnet:
